services:
  liora:
    image: docker.io/jannchie/liora:latest
    build: .
    container_name: liora
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/data/data.db"
      S3_ENDPOINT: ""
      S3_BUCKET: ""
      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      # admin credentials
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "12345678"
      # ADMIN_SESSION_SECRET: ""
    volumes:
      - ./data:/data
    restart: unless-stopped
