services:
  liora:
    image: docker.io/jannchie/liora:latest
    build: .
    container_name: liora
    ports:
      - '3000:3000'
    environment:
      S3_ENDPOINT: ''
      S3_BUCKET: ''
      S3_ACCESS_KEY_ID: ''
      S3_SECRET_ACCESS_KEY: ''
      ADMIN_USERNAME: ''
      ADMIN_PASSWORD: ''
      ADMIN_SESSION_SECRET: ''
    volumes:
      - ./data:/data
    restart: unless-stopped
